import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <>
        <header className="bg-body-tertiary">
          <nav className="navbar d-flex flex-row  px-5 py-2">
            <a className="navbar-brand">LOGO</a>
            <form
              className="d-flex"
              role="search"
            >
              <input
                className="form-control me-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
              />
              <button
                className="btn btn-outline-success"
                type="submit"
              >
                Search
              </button>
            </form>
          </nav>
        </header>
        <main className={styles.main}>
          <div className="container">
            <h1 className="text-center mt-5">
              Welcome to My Next.js App with Bootstrap
            </h1>
          </div>
        </main>
        <footer className={styles.footer}>footer</footer>
      </>
    </>
  );
}
